use mydata;
select * from mytable;
# what is the total revenue generated by male vs female customers
select gender,sum(purchase_amount) as revenue
from mytable
group by gender;

# which customer used a discount but still spent more than the average purchase amount
SELECT customer_id, purchase_amount
FROM mytable
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM mytable
  );


#which are the top 5 products with the highest average review rating
select item_purchased,round(avg(review_rating),2) as "average_product_rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;
SELECT user FROM mysql.user;

#compare the average purchase amount betweeen standard and express shhipping
select shipping_type,
round(avg(purchase_amount),2)
from mytable
where shipping_type in ('standard','express')
group by shipping_type;


#do subscribed customers spend more? compare average spend and total revenue betweeen subsscribed and non subscribed
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM mytable
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;



#which 5 products have the highest percentage of purchase with the discount applied


#segment the customers into new,returning,and loyal based on theri total number of previous purchasesf,and show the count of each segment
with customer_type as (
select customer_id,previous_purchases,
case
when previous_purchases=1 then 'New'
when previous_purchases between 2 AND 10 THEN 'Returning'
else 'Loyal'
end as customer_segment
from mytable
)

select customer_segment,count(*) as "Number of customers"
from customer_type
group by customer_segment;


#what are the top 3 most purchased products within each category





